- name: Install Collectd packages
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
   - collectd
   - collectd-apache
   - collectd-curl_json
   - collectd-mysql
   - collectd-redis
   - MySQL-python
  when: ansible_os_family == 'RedHat'  

- name: Install Collectd packages
  apt: name={{ item }} state=present
  with_items:
   - collectd
   - python-mysqldb
  when: ansible_os_family == 'Debian'  
