---
- include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: install.yml

- name: Create mysql user
  mysql_user: host="{{ item['host'] | default('localhost') }}" user="{{ item['user'] }}" password="{{ item['pass'] }}" priv="*.*:replication client"
  with_items:
    - "{{ collectd_mysql_instances }}"
  when: "'mysql' in collectd_plugins + collectd_extra_plugins and item['create_user'] is defined and item['create_user']"

- name: create collectd config directory
  file: path="{{ collectd_conf_include_dir }}" state=directory

- name: Custom types definitions
  template:
    src: "types.db.j2"
    dest: "{{ collectd_conf_include_dir }}/{{ item['name'] }}.db"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ collectd_type_dbs }}"
  notify:
    - restart collectd

- name: Update configuration
  template:
    src: "collectd.conf.j2"
    dest: "{{ collectd_conf_include_dir }}/10_collectd.conf"
    validate: 'collectd -t -C %s'
    owner: root
    group: root
    mode: 0644
  notify:
    - restart collectd

- name: Update configuration
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ collectd_conf_include_dir }}/20_{{ item }}.conf"
    validate: 'collectd -t -C %s'
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ collectd_plugins + collectd_extra_plugins }}"
  notify:
    - restart collectd

- name: Update configuration
  template:
    src: "chains.conf.j2"
    dest: "{{ collectd_conf_include_dir }}/30_chains.conf"
    # validate: 'collectd -t -C %s' # Validation fails since the dependent plugins are not loaded
    owner: root
    group: root
    mode: 0644
  when: collectd_chains is defined
  notify:
    - restart collectd
